// Generated by CoffeeScript 1.3.1
(function() {
  var Sample,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Sample = (function(_super) {

    __extends(Sample, _super);

    Sample.name = 'Sample';

    function Sample() {
      return Sample.__super__.constructor.apply(this, arguments);
    }

    Sample.prototype.init = function() {
      var _this = this;
      $('#btnRun').remove();
      return this.getConfiguration('categories', function(error, json) {
        var $option, $select, categories, category, name, _i, _len;
        categories = json;
        name = 'text';
        $select = $('<select>');
        for (_i = 0, _len = categories.length; _i < _len; _i++) {
          category = categories[_i];
          $option = $('<option>', {
            text: category,
            value: category
          });
          $select.append($option);
        }
        _this.getData(name, function(error, json) {
          var $li, $ul, data, tweet, _j, _len1;
          if (!error) {
            data = json[name];
            $('body').append($('<ul>', {
              id: 'tweetList'
            }));
            $ul = $('#tweetList');
            for (_j = 0, _len1 = data.length; _j < _len1; _j++) {
              tweet = data[_j];
              $li = $('<li>');
              $li.append($select.clone());
              $li.append($('<span>', {
                text: tweet.value
              }));
              $ul.append($li);
            }
          } else {
            alert('FUUUUUUU');
          }
          $('body').append($('<button>', {
            text: 'Send results',
            click: _this.run
          }));
        });
      });
    };

    Sample.prototype.run = function() {
      console.log('Run!');
      return this.send();
    };

    return Sample;

  })(uTask);

  $(function() {
    return $('#btnRun').click(function() {
      return new Sample;
    });
  });

}).call(this);
